# Generated by Django 2.0.2 on 2018-06-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallEnd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('call_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CallInitial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('call_id', models.IntegerField()),
                ('source', models.CharField(max_length=9)),
                ('destination', models.CharField(max_length=9)),
            ],
        ),
    ]
