# Generated by Django 2.0.2 on 2018-06-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callinitial',
            name='type',
        ),
    ]
